const Badge = {
  variants: {
    outline: {
      textTransform: "capitalize",
      cursor: "pointer",
      fontWeight: 500,
      fontSize: "13px",
      px: "8px",
      transition: ".13s ease",
      py: "4px",
      bg: "badge.body",
      userSelect: "none",
      boxShadow: "none",
      borderColor: "badge.border",
      borderWidth: "1px",
      borderStyle: "solid",
      outlineColor: "transparent",
      outlineWidth: "1px",
      outlineStyle: "solid",
      borderRadius: "6px",
      outlineOffset: "0px",
      letterSpacing: "1px",
      fontFamily: "system-ui",
      _hover: {bg: "white", color: "purple.black", borderColor: "white"},
      color: "badge.text",
    },
    "outline-no-interactive": {
      textTransform: "capitalize",
      cursor: "pointer",
      fontWeight: 600,
      fontSize: "12px",
      px: "8px",
      transition: ".13s ease",
      py: "2px",
      bg: "badge.body",
      userSelect: "none",
      boxShadow: "none",
      border: "none",
      outlineColor: "transparent",
      outlineWidth: "1px",
      outlineStyle: "solid",
      borderRadius: "4px",
      outlineOffset: "0px",
      letterSpacing: "1px",
      fontFamily: "system-ui",
      color: "badge.text",
    },

    "outline-yellow": {
      borderColor: "#fefcbf",
      borderWidth: ".5px",
      borderRadius: "6px",
      px: "2",
      fontSize: "11px",
      fontWeight: 600,
      background: "transparent",
      color: "white",
    },
  },
};

export default Badge;
