import {extendTheme} from "@chakra-ui/react";

const Button = {
  variants: {
    "solid-blue": {
      textTransform: "capitalize",
      cursor: "pointer",
      fontWeight: 500,
      fontSize: "13px",
      px: "8px",
      h: "min-content",
      py: "4px",
      bg: "badge.body",
      userSelect: "none",
      boxShadow: "none",
      borderColor: "badge.border",
      borderWidth: "1px",
      borderStyle: "solid",
      outlineColor: "transparent",
      outlineWidth: "1px",
      outlineStyle: "solid",
      borderRadius: "4px",
      outlineOffset: "0px",
      letterSpacing: "1px",
      fontFamily: "system-ui",
      _hover: {bg: "#273043", color: "purple.black", borderColor: "#464b57"},
      color: "badge.text",
    },
    "solid-hover-purple": {
      color: "white",
      bg: "purple.dominant",
      fontSize: "xs",
      fontWeight: "500",
      outline: "1px solid transparent",
      outlineOffset: "-1px",
      letterSpacing: "1.05px",
      _hover: {
        bg: "transparent",
        color: "purple.dominant",
        outlineColor: "purple.dominant",
      },
      _active: {
        bg: "purple.dominant",
      },
    },
    solid: {
      color: "white",
      bg: "purple.dominant",
      fontSize: "xs",
      fontWeight: "500",
      outline: "1px solid transparent",
      outlineOffset: "-1px",
      letterSpacing: "1.05px",
      _hover: {
        bg: "transparent",
        outlineColor: "purple.dominant",
      },
      _active: {
        bg: "purple.dominant",
      },
    },
    "solid-green": {
      color: "white",
      bg: "#027345",
      fontSize: "xs",
      fontWeight: "500",
      outline: "1px solid transparent",
      outlineOffset: "-1px",
      letterSpacing: "1.05px",
      _hover: {
        bg: "transparent",
        outlineColor: "#027345",
      },
      _active: {
        bg: "#027345",
      },
    },
    outline: {
      color: "gray",
      bg: "transparent",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "gray.medium",
      fontSize: "xs",
      fontWeight: "400",
      letterSpacing: "1.05px",
      _active: {
        borderColor: "white",
        fontWeight: 500,
        color: "purple.black",
        backgroundColor: "white",
      },
      _disabled: {
        fontWeight: "400",
        cursor: "not-allowed",
        borderColor: "gray",
        color: "gray",
        backgroundColor: "transparent",
      },
      _hover: {borderColor: "white", color: "purple.black"},
    },
    "outline-black": {
      color: "gray",
      bg: "transparent",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "gray.medium",
      fontSize: "xs",
      fontWeight: "400",
      letterSpacing: "1.05px",
      _active: {
        borderColor: "white",
        fontWeight: 500,
        color: "purple.black",
        backgroundColor: "white",
      },
      _disabled: {
        fontWeight: "400",
        cursor: "not-allowed",
        borderColor: "gray",
        color: "gray",
        backgroundColor: "transparent",
      },
      _hover: {borderColor: "white", color: "purple.black"},
    },
    rounded: {
      bg: "white",
      borderRadius: 200,
      display: "inline-flex",
      padding: 0,
    },
    gradientToPurple: {
      _hover: {bg: "linear-gradient(70deg,#f4c4f3,#fc67fa)"},
      bg: "linear-gradient(90deg, #460BF9, #D30DF3)",
      boxShadow: "0 0 5px rgba(0,0,0,0.3)",
      color: "white",
      fontSize: "xs",
      fontWeight: 500,
      height: 12,
    },
    solidGray: {
      _hover: {bg: "hsla(0, 0%, 100%, .3)"},
      bg: "hsla(0, 0%, 100%, .1)",
      fontSize: "xs",
      fontWeight: 400,
      letterSpacing: "1.05px",
      boxShadow: "0 0 5px rgba(0, 0, 0, 0.3)",
      color: "white",
      height: 12,
    },
    gradientToGreen: {
      _hover: {
        bg: "linear-gradient(80.2deg, #007644 26.08%, rgba(158, 7, 89, 0.36) 209.26%)",
      },
      bg: "transparent",
      boxShadow: "0 0 5px rgba(0, 0, 0, 0.3)",
      color: "white",
      _active: {
        bg: "linear-gradient(80.2deg, #007644 26.08%, rgba(158, 7, 89, 0.36) 209.26%)",
        transform: "scale(0.98)",
      },
      _focus: {
        bg: "linear-gradient(80.2deg, #007644 26.08%, rgba(158, 7, 89, 0.36) 209.26%)",
        boxShadow: "0 0 1px 2px rgba(88, 144, 255, 0.75), 0 1px 1px rgba(0, 0, 0, 0.15)",
      },
      fontSize: "xs",
      fontWeight: 500,
      height: 10,
      width: 120,
      border: "1px solid #FFFFFF33",
    },
    gradientToBlue: {
      _hover: {
        bg: "linear-gradient(80.2deg, #323096 19.24%, rgba(158, 7, 89, 0.36) 281.73%)",
      },
      bg: "transparent",
      boxShadow: "0 0 5px rgba(0, 0, 0, 0.3)",
      transition: "all 0.2s cubic-bezier(0.08, 0.52, 0.52, 1)",
      _active: {
        bg: "linear-gradient(80.2deg, #323096 19.24%, rgba(158, 7, 89, 0.36) 281.73%)",
        transform: "scale(0.98)",
      },
      _focus: {
        bg: "linear-gradient(80.2deg, #323096 19.24%, rgba(158, 7, 89, 0.36) 281.73%)",
        boxShadow: "0 0 1px 2px rgba(88, 144, 255, 0.75), 0 1px 1px rgba(0, 0, 0, 0.15)",
      },
      color: "white",
      fontSize: "xs",
      fontWeight: 500,
      height: 10,
      border: "1px solid #FFFFFF33",
      width: 120,
    },
    "outline-lightBlue": {
      _hover: {color: "title.white"},
      as: "span",
      color: "gray.medium",
      fontSize: "13px",
      alignItems: "baseline",
      bg: "badge.body",
      borderColor: "badge.border",
      borderRadius: "4px",
      borderWidth: ".5px",
      display: "inline-flex",
      h: "min-content",
      px: "3",
      py: "4px",
    },
  },
};

export default Button;
